packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.1
    rollup: ^4.52.5
    tsdown: ^0.15.12
    unplugin: ^2.3.10
    unplugin-utils: ^0.3.1
    vite: ^7.1.12
  cli:
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    pncat: ^0.7.4
  frontend:
    vue: ^3.5.22
  lint:
    eslint: ^9.39.0
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  node:
    fs-extra: ^11.3.2
  prod:
    ress: ^5.0.2
  script:
    esno: ^4.8.0
  test:
    '@vitest/coverage-v8': ^4.0.6
    '@vitest/ui': ^4.0.6
    vitest: ^4.0.6
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.3
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.19.0
  xiaohe:
    '@xiaohe01/eslint-config': ^3.1.0
    '@xiaohe01/tsconfig': ^2.0.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks