packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.2
    rollup: ^4.53.3
    tsdown: ^0.16.5
    unplugin: ^2.3.10
    unplugin-utils: ^0.3.1
    vite: ^7.2.2
  cli:
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    pncat: ^0.7.6
  frontend:
    ress: ^5.0.2
    vue: ^3.5.24
  lint:
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  node:
    fs-extra: ^11.3.2
  script:
    esno: ^4.8.0
  test:
    "@vitest/coverage-v8": ^4.0.10
    "@vitest/ui": ^4.0.10
    vitest: ^4.0.10
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.4
  types:
    "@types/fs-extra": ^11.0.4
    "@types/node": ^22.19.1
  xiaohe:
    "@xiaohe01/eslint-config": ^4.0.0
    "@xiaohe01/tsconfig": ^3.0.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks