shellEmulator: true

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.3
    rollup: ^4.55.1
    tsdown: ^0.18.4
    unplugin: ^2.3.11
    unplugin-utils: ^0.3.1
    vite: ^7.3.1
  cli:
    "@antfu/ni": ^28.1.0
    bumpp: ^10.3.2
    pncat: ^0.7.8
  frontend:
    ress: ^5.0.2
    vue: ^3.5.26
  lint:
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  node:
    fs-extra: ^11.3.3
  script:
    esno: ^4.8.0
  test:
    "@vitest/coverage-v8": ^4.0.16
    "@vitest/ui": ^4.0.16
    vitest: ^4.0.16
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.2.2
  types:
    "@types/fs-extra": ^11.0.4
    "@types/node": ^22.19.3
  xiaohe:
    "@xiaohe01/eslint-config": ^4.2.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks